adminUser:
  password: vault:daggerfrost/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:daggerfrost/pipelineUser:token
  username: cloudbees-ci-cd-staging[bot]
prow:
  hmacToken: vault:daggerfrost/prow:hmacToken
segmentWriteKey: vault:daggerfrost:segmentWriteKey
